application: uuevent
version: 1
runtime: python27
api_version: 1
threadsafe: no

builtins:
- appstats: on

libraries:
- name: jinja2
  version: 2.6

handlers:
- url: /frontend
  static_dir: frontend
- url: .*
  script: main.py
